name: "Exercice XXXXXXXXXXXXXX"
on:
  push:
    paths:                 # sur les fichiers
      - '**.yml'           # qui ont l'extension 'yml'
      - '!**/test/**.yml'  # sauf ceux qui ont un dossier parent nommé 'test'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: echo "je vérifie les fichiers YAML"
